const arrResults = [
  'suction-cups',
  'intimidate',
  'shadow-tag',
  'rough-skin',
  'wonder-guard',
  'levitate',
  'effect-spore',
  'synchronize',
  'clear-body',
  'natural-cure',
  'lightning-rod',
  'serene-grace',
  'swift-swim',
  'chlorophyll',
  'illuminate',
  'trace',
  'huge-power',
  'poison-point',
  'inner-focus',
  'magma-armor',
];
export default arrResults;
